### ISSUE TITLE
Simulated Flow from Carla

### ISSUE THREAD

**Issue by danqu130** [MasterHow/PanoFlow#3]
Thanks for opensource this work. After reading your arXiv paper, I found that the Flow360 dataset you proposed was obtained using Carla simulator. I have a question about using Carla to simulate optical flow.

I was confused by the visualization of simulated optical flow in some cases. As mentioned in the following two issues, there are obvious stratification or quantification problems. Have you encountered this problem when simluating the proposed dataset?

https://github.com/carla-simulator/carla/issues/4795
https://github.com/carla-simulator/carla/issues/5514

**Comment by MasterHow** [comment]
Hi! Thanks for attention.

Regarding the optical flow of CARLA, we also found that the ground truth was unreliable at the beginning of the simulation, so we rewrote the function to obtain the optical flow (via imu sensor and 3D coordinates), and verified the collected optical flow based on the forward-backward check and the Mean wArped pixel Error (MAE). Specifically, MAE refers to the pixel-by-pixel difference between two frames of images after warping the image using optical flow. We tested based on the demo collected images of the dataset, and the results are shown in the figure below. It can be seen that the MAE in all views is significantly reduced after loading the optical flow distortion, except for the down camera, which may be due to the fact that the ground is almost unchanged in the two frames before and after the motion, but an error is introduced due to the warped extra black area:
![MAE](https://user-images.githubusercontent.com/44900255/177075747-ef1d49ca-0a24-41bd-b123-0780b538e871.png)

For reference, the MAE of the training split of the Sintel dataset is about 3.8 pixels, and we have not performed statistics on the entire Flow360 for now (it may be necessary to remove sky pixels for statistics).

Unfortunately, this part of the optical flow generation function is the property of my internship company, and I have no right to decide to open source this part of the code. If you need more information, such as business or academic collaborations, please contact me further: haoshi@zju.edu.cn

**Comment by MasterHow** [comment]
Hi! Thanks for attention.

Regarding the optical flow of CARLA, we also found that the ground truth was unreliable at the beginning of the simulation, so we rewrote the function to obtain the optical flow (via imu sensor and 3D coordinates), and verified the collected optical flow based on the forward-backward check and the Mean wArped pixel Error (MAE). Specifically, MAE refers to the pixel-by-pixel difference between two frames of images after warping the image using optical flow. We tested based on the demo collected images of the dataset, and the results are shown in the figure below. It can be seen that the MAE in all views is significantly reduced after loading the optical flow distortion, except for the down camera, which may be due to the fact that the ground is almost unchanged in the two frames before and after the motion, but an error is introduced due to the warped extra black area:
![MAE-2](https://user-images.githubusercontent.com/44900255/177076502-5b55d219-a294-4de0-abc1-7e4c8c06783c.png)

For reference, the MAE of the training split of the Sintel dataset is about 3.8 pixels, and we have not performed statistics on the entire Flow360 for now (it may be necessary to remove sky pixels for statistics).

Unfortunately, this part of the optical flow generation function is the property of my internship company, and I have no right to decide to open source this part of the code. If you need more information, such as business or academic collaborations, please contact me further: haoshi@zju.edu.cn

**Comment by MasterHow** [comment]
> Hi! Thanks for attention.
> 
> Regarding the optical flow of CARLA, we also found that the ground truth was unreliable at the beginning of the simulation, so we rewrote the function to obtain the optical flow (via imu sensor and 3D coordinates), and verified the collected optical flow based on the forward-backward check and the Mean wArped pixel Error (MAE). Specifically, MAE refers to the pixel-by-pixel difference between two frames of images after warping the image using optical flow. We tested based on the demo collected images of the dataset, and the results are shown in the figure below. It can be seen that the MAE in all views is significantly reduced after loading the optical flow distortion, except for the down camera, which may be due to the fact that the ground is almost unchanged in the two frames before and after the motion, but an error is introduced due to the warped extra black area: ![MAE-2](https://user-images.githubusercontent.com/44900255/177076502-5b55d219-a294-4de0-abc1-7e4c8c06783c.png)
> 
> For reference, the MAE of the training split of the Sintel dataset is about 3.8 pixels, and we have not performed statistics on the entire Flow360 for now (it may be necessary to remove sky pixels for statistics).
> 
> Unfortunately, this part of the optical flow generation function is the property of my internship company, and I have no right to decide to open source this part of the code. If you need more information, such as business or academic collaborations, please contact me further: [haoshi@zju.edu.cn](mailto:haoshi@zju.edu.cn)

We supplemented the warped point error statistics on the entire Flow360 test split (including the sky), and it can be seen that the warped error of the gt flow is about 3.07 pixel, which is comparable to the level of the Sintel dataset.
![image](https://user-images.githubusercontent.com/44900255/177117641-137735db-7346-432c-97c6-95448fe69685.png)

**Comment by MasterHow** [comment]
Correction of typo: The unit of this metric is grayscale rather than pixels.

**Comment by danqu130** [comment]
Thank you for providing a verification and selection option in your reply. This result shows that the simulated flow in Flow360 is reliable. 
I found that the unreliable stratification or quantification problems not only occurs at the beginning of the simulation, but also later. I haven't found its regularity yet. 
Because your dataset is synthesized into the 360 view, I haven't downloaded it to visualize whether this problem also exists.

**Comment by MasterHow** [comment]
Hi, we suggest you refer to this [link](https://developer.nvidia.com/gpugems/gpugems3/part-iv-image-effects/chapter-27-motion-blur-post-processing-effect). Also, we are considering open source the original 6 pinhole camera dataset with optical flow and semantics together, hope this may help you.

**Comment by danqu130** [comment]
Thanks for your answer. I have found out the (possible) orginal implementation of Carla flow, but I still can't explain the reason for this abnormal simulation output. I listed the resources I found here.

https://github.com/carla-simulator/carla/blob/master/Unreal/CarlaUE4/Plugins/Carla/Content/PostProcessingMaterials/VelocityMaterial.uasset
https://github.com/carla-simulator/carla/blob/master/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/OpticalFlowCamera.cpp
https://github.com/BrainGardenAI/OptiFlow
https://github.com/ProfFan/UnrealOpticalFlowDemo

**Comment by NnaYelsel** [comment]
Hello @MasterHow 

When you say "we rewrote the function to obtain the optical flow (via imu sensor and 3D coordinates)", do you mean with Unreal engine or with python ?

Best regards.
