### ISSUE TITLE
Cannot download dataset

### ISSUE THREAD

**Issue by bainro** [MasterHow/PanoFlow#4]
The first link is broken and the second link requires I setup a chinese baidu account. I don't have a chinese email that they'll accept, nor a chinese phone number, and I can't solve their capchas either :-/ 

Is there an easier way to download the dataset?

**Comment by phifisch** [comment]
I have basically the same issue with the pretrained model. Downloading the pretrained model requires a weChat account and I can't create one (starting with the fact that I can't read what the popup tells me to do).
Could you upload to a different platform, please? Since this is a published work, maybe consider a persistent storage like Zenodo.

**Comment by christopher5106** [comment]
I have the same issue, could you please provide a link where we can download without chinese software ?

**Comment by MasterHow** [comment]
Hi, thx for your interest! We have additionally provide the Google Drive link for the Flow360 (FlowScape) dataset here: https://drive.google.com/file/d/1cKJZBRprwS6fu6Nf4U0eU6lkqB88tW_v/view?usp=sharing . Sorry for the inconvenience before. =)
